generator:
  class:                   sfPropelAdminGenerator
  param:
    model_class:           Config
    theme:                 default
    fields:
      id:                  { name: Id }
      param:               { name: Параметр }
      description:         { name: Описание }
      value:               { name: Значение }
      is_active:           { name: Акт. }
      created_at:          { name: Дата }
    list:
      title:               Категории
      layout:              tabular
      display:             [id,param,description,is_active,created_at]
      object_actions:
        _edit:             ~
        _delete:           ~
      max_per_page:        15
    edit:
      title:               Категории
      display:             [id,param,description,value,is_active,created_at]
      fields:
        name:              { type: input_tag, params: size=50x10 }
        created_at:        { type: input_date_tag, params: rich=on }
        value:             { type: textarea_tag, params: size=47x10 }
