<?php
// auto-generated by sfRoutingConfigHandler
// date: 2015/08/05 00:39:26
return array(
'homepage' => new sfRoute('/', array (
  'module' => 'default',
  'action' => 'index',
), array (
), array (
)),
'contacts' => new sfRoute('/contacts', array (
  'module' => 'contacts',
  'action' => 'index',
), array (
), array (
)),
'cart' => new sfRoute('/cart', array (
  'module' => 'cart',
  'action' => 'index',
), array (
), array (
)),
'cart_clear' => new sfRoute('/cart/clear', array (
  'module' => 'cart',
  'action' => 'clear',
), array (
), array (
)),
'cart_order' => new sfRoute('/cart/order', array (
  'module' => 'cart',
  'action' => 'order',
), array (
), array (
)),
'articles' => new sfRoute('/articles/', array (
  'module' => 'pp_articles',
  'action' => 'index',
), array (
), array (
)),
'article_id' => new sfRoute('/articles/id/:id', array (
  'module' => 'pp_articles',
  'action' => 'new',
), array (
), array (
)),
'news' => new sfRoute('/news/', array (
  'module' => 'pp_news',
  'action' => 'index',
), array (
), array (
)),
'new_id' => new sfRoute('/news/id/:id', array (
  'module' => 'pp_news',
  'action' => 'new',
), array (
), array (
)),
'parts' => new sfRoute('/parts/', array (
  'module' => 'pp_parts',
  'action' => 'index',
), array (
), array (
)),
'parts_part' => new sfRoute('/parts/id/:id/', array (
  'module' => 'pp_parts',
  'action' => 'index',
), array (
), array (
)),
'parts_new' => new sfRoute('/parts/new', array (
  'module' => 'pp_parts',
  'action' => 'new',
), array (
), array (
)),
'photos' => new sfRoute('/photos/id/:id', array (
  'module' => 'pp_photos',
  'action' => 'index',
), array (
), array (
)),
'photos_0' => new sfRoute('/photos/cart/id/:id/', array (
  'module' => 'pp_photos',
  'action' => 'cart',
), array (
), array (
)),
'photos_1' => new sfRoute('/photos/cartdel/id/:id/', array (
  'module' => 'pp_photos',
  'action' => 'cartdel',
), array (
), array (
)),
'default_index' => new sfRoute('/:module', array (
  'action' => 'index',
), array (
), array (
)),
'default' => new sfRoute('/:module/:action/*', array (
), array (
), array (
)),
'pages' => new sfRoute('/*', array (
  'module' => 'pp_pages',
  'action' => 'index',
), array (
), array (
)),
);
