<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/08/05 00:39:26

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=symfony;host=localhost',
  'username' => 'satelites',
  'password' => 'JvQRpJ0q23BgOZUIPJCVOSxp',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
