generator:
  class:                   sfPropelAdminGenerator
  param:
    model_class:           Authors
    theme:                 default
    fields:
      id:                  { name: Id }
      meta_id:             { name: Meta }
      name:                { name: Заголовок }
      is_active:           { name: Акт. }
      created_at:          { name: Дата }
    list:
      title:               Фотографы
      layout:              tabular
      display:             [id,meta_id,name,is_active,created_at]
      object_actions:
        _edit:             ~
        _delete:           ~
      max_per_page:        15
    edit:
      title:               Фотографы
      display:             [id,meta_id,name,is_active,created_at]
      fields:
        name:              { type: input_tag, params: style=width: 90%; }
        created_at:        { type: input_date_tag, params: rich=on }
