<?php


/**
 * This class adds structure of 'pp_faq' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Aug  9 02:03:44 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class FaqMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.FaqMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(FaqPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(FaqPeer::TABLE_NAME);
		$tMap->setPhpName('Faq');
		$tMap->setClassname('Faq');

		$tMap->setUseIdGenerator(true);

		$tMap->addForeignKey('META_ID', 'MetaId', 'INTEGER', 'pp_meta', 'ID', false, null);

		$tMap->addColumn('QUESTION', 'Question', 'VARCHAR', false, 1000);

		$tMap->addColumn('ANSWER', 'Answer', 'VARCHAR', false, 1000);

		$tMap->addColumn('ORD', 'Ord', 'VARCHAR', false, 255);

		$tMap->addColumn('IS_ACTIVE', 'IsActive', 'BOOLEAN', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

	} // doBuild()

} // FaqMapBuilder
