<?php


/**
 * This class adds structure of 'pp_photos' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Aug  9 02:03:44 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PhotosMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PhotosMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(PhotosPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(PhotosPeer::TABLE_NAME);
		$tMap->setPhpName('Photos');
		$tMap->setClassname('Photos');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('META_ID', 'MetaId', 'INTEGER', 'pp_meta', 'ID', false, null);

		$tMap->addColumn('NAME', 'Name', 'VARCHAR', true, 255);

		$tMap->addColumn('DESCRIPTION', 'Description', 'VARCHAR', false, 1000);

		$tMap->addForeignKey('PART_ID', 'PartId', 'INTEGER', 'pp_parts', 'ID', false, null);

		$tMap->addForeignKey('AUTHOR_ID', 'AuthorId', 'INTEGER', 'pp_authors', 'ID', false, null);

		$tMap->addColumn('PHOTO_S', 'PhotoS', 'VARCHAR', false, 255);

		$tMap->addColumn('PHOTO_B', 'PhotoB', 'VARCHAR', false, 255);

		$tMap->addColumn('SIZE', 'Size', 'VARCHAR', false, 255);

		$tMap->addColumn('PRICE', 'Price', 'INTEGER', false, null);

		$tMap->addColumn('ORD', 'Ord', 'VARCHAR', false, 255);

		$tMap->addColumn('IS_NEW', 'IsNew', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_SPEC', 'IsSpec', 'BOOLEAN', true, null);

		$tMap->addColumn('IS_ACTIVE', 'IsActive', 'BOOLEAN', true, null);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // PhotosMapBuilder
