generator:
  class:                   sfPropelAdminGenerator
  param:
    model_class:           Pages
    theme:                 default
    fields:
      id:                  { name: Id }
      meta_id:             { name: Meta }
      ord:                 { name: Сорт. }
      title:               { name: Заголовок }
      announce:            { name: Анонс }
      text:                { name: Текст }
      is_active:           { name: Акт. }
      created_at:          { name: Дата }
    list:
      title:               Страницы
      layout:              tabular
      display:             [id,ord,url,title,announce,is_active,created_at]
      object_actions:
        _edit:             ~
        _delete:           ~
      max_per_page:        15
    edit:
      title:               Страницы
      display:             [id,ord,meta_id,url,title,announce,text,is_active,created_at]
      fields:
        created_at:        { type: input_date_tag, params: rich=on }
        title:             { input_tag, params: style=width: 90%; }
        announce:          { type: textarea_tag, params: style=width: 90%; height: 100px; }
        text:              { type: textarea_tag, params: style=width: 90%; height: 100px; rich=on }